baseURL = 'https://jxxxxxlxx.github.io/'
locale = 'en-us'
title = 'JXXXXXLXX'
DefaultContentLanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[services]
  [services.googleAnalytics]
    id = "G-9V5B08KL4X"

[params]
headTitle = "JXXXXXLXX"
favicon = "/favicon.ico"
#description = "Trust the process..." 
mainSections = ["posts"]
extraCSSFiles = ["css/custom.css"]

[[params.socials]]
name = "Home"
link = "/"

#[[params.socials]]
#name = "About"
#link = "/about/"

[[params.socials]]
name = "Tags"
link = "/tags/"

[[params.socials]]
name = "RSS"
link = "/index.xml"
